/* Pure demo state machine. No production API or permission mutations. */
(function(root){
'use strict';
const clone=x=>JSON.parse(JSON.stringify(x));
const scenarios={
 cross:{name:'跨域高价值发现',query:'圈出电商消费较低、但生服消费较高的潜在高价值用户',domain:'跨域',object:'跨域潜在高价值用户',signal:'两域消费分层同时满足',source:'PRD · 跨域高价值人群捞取',failure:'mapping',fields:['电商消费分层','生服消费分层','跨域关联标识']},
 travel:{name:'土地公个性化圈人',query:'圈出近期有出游意向、偏好中高端住宿、在土地公有咨询行为的用户',domain:'生服',object:'土地公咨询用户中的出游与住宿偏好人群',signal:'出游信号 AND 住宿偏好 AND 咨询行为',source:'PRD · 土地公场景',failure:'stale',fields:['出游意向标签','住宿偏好标签','土地公咨询行为']},
 brand:{name:'品牌营销圈人',query:'给波司登找对羽绒服感兴趣、近90天有服饰消费、中高消费能力的用户',domain:'跨域',object:'波司登羽绒服目标用户',signal:'羽绒服兴趣 AND 服饰成交 AND 消费分层',source:'PRD · 品牌营销案例',failure:'definition',fields:['服饰兴趣标签','服饰成交记录','消费能力分层']},
 uplift:{name:'实验高增益人群',query:'找出这个实验里对发券最敏感的20%用户',domain:'生服',object:'发券高增益候选人群',signal:'已存在的 Uplift 分数前20%',source:'PRD · Uplift 场景',failure:'model',fields:['实验 Uplift 分数','实验合格用户范围']},
 theme:{name:'榜单主题圈人',query:'为通勤穿搭榜单圈出相关兴趣人群',domain:'跨域',object:'通勤穿搭兴趣人群',signal:'主题关联兴趣标签',source:'PRD · 毕喆榜单主题案例',failure:'missing',fields:['主题兴趣标签','用户偏好标签']},
 custom:{name:'自定义圈人任务',query:'',domain:'生服',object:'',signal:'',source:'业务原话 · 人工确认',failure:'missing',fields:['待匹配核心资产']}
};
const blockers={missing:'核心资产缺失',permission:'权限不足',definition:'核心口径待确认',mapping:'跨域 ID 映射不可用',stale:'资产过期',model:'Uplift 模型结果缺失',sample:'结果样本量过小',sql:'SQL 执行失败'};
function classify(q){if(/建表|建设底表|新增字段/.test(q))return '基建';if(/年度规划|业务规划|明年方向/.test(q))return '规划';if(/开发|上线弹窗|新建功能/.test(q)&&!/圈|筛选/.test(q))return '功能';if(/分析|特点|为什么/.test(q)&&!/圈|筛选|找出/.test(q))return '分析';return /复用|历史策略/.test(q)?'复用历史策略':'直接圈人';}
function detect(q){if(/发券|uplift|增益/i.test(q))return 'uplift';if(/波司登|羽绒服/.test(q))return 'brand';if(/出游|住宿|酒店/.test(q))return 'travel';if(/通勤|榜单/.test(q))return 'theme';if(/电商/.test(q)&&/生服/.test(q))return 'cross';return 'custom';}
function create(q,key,scope='portal'){
 key=key||detect(q);const s=scenarios[key];const stamp=Date.now();return {schema:1,id:'DEMO-'+stamp.toString(36).toUpperCase()+'-'+Math.random().toString(36).slice(2,5).toUpperCase(),title:s.name,created:new Date().toISOString(),query:q,scenario:key,scope,stage:1,version:1,type:classify(q),fields:{object:{value:s.object,status:key==='custom'?'待确认':'系统推断'},action:{value:'',status:'待确认'},window:{value:/90\s*天/.test(q)?'90':'',status:/90\s*天/.test(q)?'已明确':'待确认'},domain:{value:s.domain,status:'系统推断'},definition:{value:'',status:'待确认'},platform:{value:'',status:'待确认'},exclude:{value:'',status:'待确认'},success:{value:'',status:'待确认'},experiment:{value:'',status:'待确认'}},notes:[],materials:[],confirmed:false,strategy:null,strategyConfirmed:false,conditions:[],conditionConfirmed:false,blocker:null,attempts:0,runs:[],result:null,versions:[],history:[],archived:false,adoption:'未采纳',destination:'',reuse:false,attachedAssets:[],metrics:{revisions:0},feedback:''};
}
function log(t,action){t.history.push({at:new Date().toISOString(),version:t.version,action,actor:'当前演示用户'});}
function missing(t){const keys=['object','action','window','domain','definition','platform','exclude','success'];if(t.scenario==='uplift')keys.push('experiment');return keys.filter(k=>!t.fields[k].value.trim()||!['已确认','已明确','不适用'].includes(t.fields[k].status));}
function confirm(t){if(!['直接圈人','复用历史策略','分析转圈人'].includes(t.type))throw Error('该请求不在当前圈人执行范围');if(missing(t).length)throw Error('请先确认全部必要信息');if(t.scope==='ldmp'&&t.fields.domain.value==='跨域')throw Error('LDMP 演示仅限生服资产，请回门户创建跨域任务');t.confirmed=true;t.stage=2;log(t,'需求理解单已确认');}
function select(t,ids){if(!t.confirmed)throw Error('请先确认需求');if(!ids.length)throw Error('请选择策略');t.strategy={ids,note:'',evidence:scenarios[t.scenario].source};t.strategyConfirmed=true;t.stage=3;t.conditions=scenarios[t.scenario].fields.map((name,i)=>({id:'DEMO-ASSET-'+t.scenario+'-'+i,name,domain:t.fields.domain.value==='跨域'?(i%2?'生服':'电商'):'生服',owner:'演示供应方',assetVersion:'demo.1',updated:'2026-09-28',definition:t.fields.definition.value,group:'必须满足',operator:'符合',value:t.fields.definition.value,core:true,permission:'演示可用'}));t.conditions.push({id:'DEMO-GUARD',name:'营销授权与业务排除',domain:'平台',owner:'演示治理规则',assetVersion:'demo.1',updated:'2026-09-28',definition:t.fields.exclude.value,group:'排除',operator:'排除',value:t.fields.exclude.value,core:true,locked:true,permission:'演示可用'});t.conditions.unshift({id:'DEMO-SIGNAL',name:'策略证据强度',domain:t.fields.domain.value,owner:'演示策略配置',assetVersion:'demo.1',updated:'2026-09-28',definition:'候选策略对应的示例信号范围，仍需确认',group:'必须满足',operator:'符合',value:ids.map(id=>({conservative:'强信号',balanced:'中强信号',explore:'弱信号待验证',direct:'业务完整定义'}[id]||id)).join(' 或 '),core:true,permission:'演示可用'});t.conditionConfirmed=false;log(t,'策略已确认，构建演示条件');}
function executable(t){return t.confirmed&&t.strategyConfirmed&&t.conditionConfirmed&&!t.blocker&&t.conditions.length>0&&t.conditions.every(c=>c.value.trim()&&c.permission==='演示可用')&&!(t.scope==='ldmp'&&t.fields.domain.value==='跨域');}
function snapshot(t,reason){return {version:t.version,reason,at:new Date().toISOString(),fields:clone(t.fields),strategy:clone(t.strategy),conditions:clone(t.conditions),result:clone(t.result),confirmed:t.confirmed,strategyConfirmed:t.strategyConfirmed,conditionConfirmed:t.conditionConfirmed};}
function revise(t,level,reason){t.versions.push(snapshot(t,reason));t.version++;t.metrics.revisions++;t.result=null;t.archived=false;t.conditionConfirmed=false;t.stage=level;if(level<=1){t.confirmed=false;t.strategyConfirmed=false;t.strategy=null;t.conditions=[];}else if(level<=2){t.strategyConfirmed=false;}log(t,reason+'；下游结果待重算');}
function sql(t){const cond=JSON.stringify({window:t.fields.window.value,strategy:t.strategy,conditions:t.conditions.map(c=>({group:c.group,asset:c.id,value:c.value}))});return '-- 演示 SQL · 无真实表映射，不可用于生产\n-- task '+t.id+' / v'+t.version+'\n-- 确认条件 '+cond.replace(/[\r\n]/g,' ')+'\nSELECT demo_user_id\nFROM demo_authorized_audience\nWHERE demo_rule_version = '+t.version+';';}
function run(t,fail){if(!executable(t))throw Error('核心条件未通过校验，禁止执行');if(t.attempts>=3)throw Error('连续三轮未达标，已停止自动尝试，请转人工');t.stage=4;const run={id:'DEMO-RUN-'+(t.runs.length+1),version:t.version,at:new Date().toISOString(),sql:sql(t),status:fail?'失败':'完成',reason:fail?blockers[fail]||fail:null};t.runs.push(run);if(fail){t.attempts++;log(t,run.reason);return run;}t.attempts=0;t.result={version:t.version,runId:run.id,size:12840+t.conditions.length*237,coverage:87,seed:t.seedRef?92:null,excluded:1360,missing:42,partition:'DEMO / 2026-09-27',sql:run.sql,approved:false,sampleIds:['DEMO-USER-001','DEMO-USER-002','DEMO-USER-003']};log(t,'模拟执行完成，等待业务复核');return run;}
function approve(t){if(!t.result||t.result.version!==t.version||t.blocker)throw Error('无当前有效结果');t.result.approved=true;t.stage=5;log(t,'业务复核通过，MVP 方案完成（演示）');}
function restore(t,v){const target=t.versions.find(x=>x.version===v);if(!target)throw Error('版本不存在');revise(t,1,'从 v'+v+'恢复为新版本');t.fields=clone(target.fields);Object.values(t.fields).forEach(f=>{if(f.status==='已确认')f.status='待确认';});}
const api={scenarios,blockers,clone,classify,detect,create,log,missing,confirm,select,executable,snapshot,revise,run,approve,restore,sql};if(typeof module!=='undefined')module.exports=api;root.AudienceEngine=api;
})(typeof window!=='undefined'?window:globalThis);
